<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CodeWordle</title>
    <!-- Bootstrap 5 CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background-color: #121213;
            color: #fff;
        }
        .container {
            max-width: 500px;
        }
        .header {
            border-bottom: 1px solid #3a3a3c;
        }
        .tile {
            width: 62px;
            height: 62px;
            border: 2px solid #3a3a3c;
            font-size: 2rem;
            font-weight: bold;
            text-transform: uppercase;
            display: inline-flex;
            justify-content: center;
            align-items: center;
            transition: transform 0.6s, background-color 0.6s, border-color 0.6s;
            transform-style: preserve-3d;
        }
        .tile.flipping {
            transform: rotateX(180deg);
        }
        .tile.correct-position {
            background-color: #538d4e;
            border-color: #538d4e;
        }
        .tile.wrong-position {
            background-color: #b59f3b;
            border-color: #b59f3b;
        }
        .tile.not-in-word {
            background-color: #3a3a3c;
            border-color: #3a3a3c;
        }
    </style>
</head>
<body>

<div class="container text-center py-4">
    <header class="header mb-4 pb-3">
        <h1>CodeWordle</h1>
    </header>

    <!-- Game Setup Area (Visible at start) -->
    <section id="game-setup" class="my-4">
        <h2>Select a Topic</h2>
        <form id="start-form">
            <c:forEach var="topic" items="${topics}">
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="topicId" id="topic-${topic.id}" value="${topic.id}" required>
                    <label class="form-check-label" for="topic-${topic.id}">${topic.name}</label>
                </div>
            </c:forEach>
            <div class="d-grid gap-2 mt-3">
                <button type="submit" class="btn btn-primary btn-lg">Start Game</button>
            </div>
        </form>
    </section>

    <!-- Main Game Area (Hidden at start) -->
    <main id="game-area" class="d-none">
        <div id="game-board" class="d-flex flex-column align-items-center gap-1 mb-4">
            <!-- Game tiles will be generated by JavaScript -->
        </div>
        <form id="guess-form">
            <div class="input-group mb-3">
                <input type="text" id="guess-input" class="form-control form-control-lg text-uppercase" placeholder="Enter your guess" required autofocus>
                <button type="submit" class="btn btn-success">Guess</button>
            </div>
        </form>
    </main>

    <!-- Notification Area -->
    <div id="notification-area" class="mt-3"></div>

</div>

<!-- JavaScript Logic -->
<script>
    document.addEventListener('DOMContentLoaded', function () {
        // --- STATE VARIABLES ---
        let currentGameId = null;
        let currentAttemptRow = 0;
        let wordLength = 0;
        const MAX_ATTEMPTS = 6;

        // --- DOM ELEMENTS ---
        const startForm = document.getElementById('start-form');
        const gameSetupDiv = document.getElementById('game-setup');
        const gameAreaDiv = document.getElementById('game-area');
        const gameBoard = document.getElementById('game-board');
        const guessForm = document.getElementById('guess-form');
        const guessInput = document.getElementById('guess-input');
        const notificationArea = document.getElementById('notification-area');

        // --- EVENT LISTENERS ---
        startForm.addEventListener('submit', handleStartGame);
        guessForm.addEventListener('submit', handleGuessSubmit);

        /**
         * Handles the "Start Game" button click.
         */
        async function handleStartGame(event) {
            event.preventDefault();
            const selectedTopic = document.querySelector('input[name="topicId"]:checked');
            if (!selectedTopic) {
                showNotification('Please select a topic!', 'warning');
                return;
            }

            const topicId = selectedTopic.value;
            const url = `<c:url value='/api/games/start'/>?topicId=${topicId}`;

            try {
                const response = await fetch(url, { method: 'POST' });
                if (!response.ok) {
                    throw new Error(await response.text());
                }
                const newGame = await response.json();

                // Initialize game state from backend response
                // NOTE: The backend sends back the whole Game object, but not the word itself.
                // We need another way to get the word length. Let's make another call or adjust the API.
                // For now, let's assume we can get it from a call that would fetch word details
                // A better approach would be to have the START api return the word length.
                // LET'S SIMPLIFY: for now we process the attempt and infer length from the feedback
                currentGameId = newGame.id;
                currentAttemptRow = 0;

                // Transition UI from setup to game
                gameSetupDiv.classList.add('d-none');
                gameAreaDiv.classList.remove('d-none');
                showNotification('Game started! Good luck.', 'info');
                guessInput.focus();
            } catch (error) {
                showNotification(`Error starting game: ${error.message}`, 'danger');
            }
        }

        /**
         * Handles the guess submission.
         */
        async function handleGuessSubmit(event) {
            event.preventDefault();
            const guessedWord = guessInput.value.trim();

            if (!guessedWord) return;

            // Simple client-side length validation if wordLength is known
            if (wordLength > 0 && guessedWord.length !== wordLength) {
                showNotification(`Your guess must be ${wordLength} letters long.`, 'warning');
                return;
            }

            const url = `<c:url value='/api/games/'/>${currentGameId}/attempts`;

            try {
                const response = await fetch(url, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ word: guessedWord })
                });

                if (!response.ok) {
                    throw new Error(await response.text());
                }

                const attemptResponse = await response.json();

                if(wordLength === 0) {
                    wordLength = attemptResponse.feedback.length;
                    setupGameBoard(wordLength); // Setup board on first successful guess
                    guessInput.maxLength = wordLength;
                }

                updateBoard(attemptResponse.feedback, guessedWord.toUpperCase());

                // Check game over conditions
                if (attemptResponse.gameStatus !== 'IN_PROGRESS') {
                    handleGameOver(attemptResponse);
                } else {
                    currentAttemptRow++;
                    guessInput.value = ''; // Clear input for next guess
                }
            } catch (error) {
                showNotification(`Error: ${error.message}`, 'danger');
            }
        }

        /**
         * Creates the grid of tiles for the game board.
         */
        function setupGameBoard(length) {
            gameBoard.innerHTML = ''; // Clear previous board
            for (let i = 0; i < MAX_ATTEMPTS; i++) {
                const row = document.createElement('div');
                row.className = 'd-flex gap-1';
                for (let j = 0; j < length; j++) {
                    const tile = document.createElement('div');
                    tile.className = 'tile';
                    row.appendChild(tile);
                }
                gameBoard.appendChild(row);
            }
        }

        /**
         * Updates the board with feedback from the server.
         */
        function updateBoard(feedback, guessedWord) {
            const row = gameBoard.children[currentAttemptRow];
            for (let i = 0; i < feedback.length; i++) {
                const tile = row.children[i];
                tile.textContent = guessedWord[i];

                setTimeout(() => {
                    tile.classList.add('flipping');
                    let statusClass = '';
                    switch (feedback[i].status) {
                        case 'CORRECT_POSITION': statusClass = 'correct-position'; break;
                        case 'WRONG_POSITION':   statusClass = 'wrong-position'; break;
                        case 'NOT_IN_WORD':      statusClass = 'not-in-word'; break;
                    }
                    tile.classList.add(statusClass);
                }, i * 300); // Staggered flip animation
            }
        }

        /**
         * Handles the end of the game (win or lose).
         */
        function handleGameOver(response) {
            guessInput.disabled = true;
            guessForm.querySelector('button').disabled = true;

            let message = '';
            let type = '';
            if (response.gameStatus === 'WON') {
                message = 'Congratulations, you won!';
                type = 'success';
            } else {
                message = `Game over! The correct word was: <strong>${response.correctWord}</strong>`;
                type = 'danger';
            }

            setTimeout(() => {
                showNotification(message, type, false); // Don't auto-dismiss

                // Add a "Play Again" button
                const playAgainBtn = document.createElement('button');
                playAgainBtn.className = 'btn btn-info mt-3';
                playAgainBtn.textContent = 'Play Again';
                playAgainBtn.onclick = resetUI;
                notificationArea.appendChild(playAgainBtn);

            }, wordLength * 300 + 500); // Wait for the flip animation to finish
        }

        /**
         * Resets the UI to the initial state to start a new game.
         */
        function resetUI() {
            gameAreaDiv.classList.add('d-none');
            gameSetupDiv.classList.remove('d-none');
            notificationArea.innerHTML = '';
            guessInput.disabled = false;
            guessInput.value = '';
            guessInput.maxLength = 524288; // reset maxlength
            guessForm.querySelector('button').disabled = false;
            wordLength = 0;
            currentGameId = null;
        }

        /**
         * A utility function to show messages to the user.
         */
        function showNotification(message, type = 'info', autoDismiss = true) {
            notificationArea.innerHTML = `<div class="alert alert-${type}" role="alert">${message}</div>`;
            if (autoDismiss) {
                setTimeout(() => {
                    notificationArea.innerHTML = '';
                }, 4000);
            }
        }
    });
</script>

</body>
</html>